services:
  - type: web
    name: laravel-api
    env: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
      php artisan migrate --force
      npm install
      npm run production
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
